In [1]:
import numpy as np

'''**Задание на повторение материала
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
'''

In [2]:
a = np.array(range(12,23))

'''Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
'''

In [6]:
a1 = np.reshape(a[0:4], (2,2))
a2 = np.reshape(a[1:7], (2,3))
a3 = np.reshape(a[0:9], (3,3))
a4 = np.reshape(a[3:9], (2,3))
a5 = np.reshape(a[0:7:2], (2,2))
print(a1, '\n', a2, '\n', a3, '\n', a4, '\n', a5)

[[12 13]
 [14 15]] 
 [[13 14 15]
 [16 17 18]] 
 [[12 13 14]
 [15 16 17]
 [18 19 20]] 
 [[15 16 17]
 [18 19 20]] 
 [[12 14]
 [16 18]]


'''Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - да
'''

In [7]:
a1 = np.reshape(a[0:4], (2,-1))
a2 = np.reshape(a[1:7], (2,-1))
a3 = np.reshape(a[0:9], (3,-1))
a4 = np.reshape(a[3:9], (-1,3))
a5 = np.reshape(a[0:7:2], (-1,2))
print(a1, '\n', a2, '\n', a3, '\n', a4, '\n', a5)

[[12 13]
 [14 15]] 
 [[13 14 15]
 [16 17 18]] 
 [[12 13 14]
 [15 16 17]
 [18 19 20]] 
 [[15 16 17]
 [18 19 20]] 
 [[12 14]
 [16 18]]


'''Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
'''


In [18]:
a = np.random.randn(3,4, (0,1))
print(a, np.average(a))

TypeError: 'tuple' object cannot be interpreted as an integer

'''Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.'''

In [19]:
np.random.rand?